CC=gcc
CFLAGS =-Wall
EXEC_NAME = ./bin/RPly_convert
INCLUDES =./src/rply.h ./src/rply.c ./src/convert.c 
LIBS =
OBJ_FILES = ./bin/rply.o ./bin/convert.o
INSTALL_DIR = ./

all :
	gcc $(CFLAGS) $(INCLUDES) -o $(EXEC_NAME)

test : 
	all :
	./bin.RPly_convert -a_nh ./data/
